#!/bin/bash

source ${EOS_SCRIPT_PATH}/job.bash

export EOS_ANALYSIS_INFO=0

export EOS_IS_INTEGRATION_POINTS=16
export EOS_IS_SAMPLES=51200

export EOS_MCMC_BURN_IN=500
export EOS_MCMC_PROPOSAL='gauss'
export EOS_MCMC_SAMPLES=50000
export EOS_MCMC_SCALE_REDUCTION=5
export EOS_MCMC_UPDATE_SIZE=500

export EOS_VB_COMPONENTS_PER_GROUP=20
export EOS_VB_EXTRA_OPTIONS='--rel-tol 0.000001'
export EOS_VB_PRUNE=100
export EOS_VB_SKIP_INITIAL=0.5
export EOS_VB_THIN=100

main $@
