#!/bin/bash

source ${EOS_SCRIPT_PATH}/job.bash

export EOS_ANALYSIS_INFO=1
export EOS_SEED=32174924

export EOS_IS_INTEGRATION_POINTS=16
export EOS_IS_SAMPLES=100000

export EOS_MCMC_BURN_IN=
export EOS_MCMC_COVARIANCE="Kstar-FF-cov.txt"
export EOS_MCMC_INITIAL_VALUES="fixed"
export EOS_MCMC_PROPOSAL='gauss'
export EOS_MCMC_SAMPLES=500000
export EOS_MCMC_SCALE_REDUCTION=3
export EOS_MCMC_UPDATE_SIZE=500

export EOS_VB_COMPONENTS_PER_GROUP=3
export EOS_VB_PRUNE=200
export EOS_VB_REL_TOL=0.0001
export EOS_VB_SKIP_INITIAL=0.4
export EOS_VB_THIN=100

main $@
