#!/bin/bash

source ${EOS_SCRIPT_PATH}/job.bash

export EOS_ANALYSIS_INFO=1
export EOS_SEED=8795487

export EOS_IS_SAMPLES=10000

export EOS_MCMC_SCALE_REDUCTION=5
export EOS_MCMC_BURN_IN=500
export EOS_MCMC_UPDATE_SIZE=500
export EOS_MCMC_SAMPLES=50000
export EOS_MCMC_PROPOSAL='gauss'

export EOS_VB_COMPONENTS_PER_GROUP=15
export EOS_VB_EXTRA_OPTIONS='--rel-tol 0.000001'
export EOS_VB_PRUNE=200
export EOS_VB_R_VALUE=2
export EOS_VB_SKIP_INITIAL=0.30
export EOS_VB_THIN=50

main $@
