#!/bin/bash

source ${EOS_SCRIPT_PATH}/job.bash

export EOS_SEED=8793218
export EOS_ANALYSIS_INFO=1

export EOS_IS_SEED=1379821987
export EOS_IS_SAMPLES=100000

export EOS_MCMC_COVARIANCE="Kstar-FF-cov.txt"
export EOS_MCMC_INITIAL_VALUES="fixed"
export EOS_MCMC_PROPOSAL='gauss'
export EOS_MCMC_SAMPLES=150000
export EOS_MCMC_UPDATE_SIZE=500

export EOS_VB_COMPONENTS_PER_GROUP=3
export EOS_VB_REL_TOL=0.0001
export EOS_VB_SKIP_INITIAL=0
export EOS_VB_THIN=1

main $@
