#!/bin/bash
#vim: set sts=4 et :

source ${EOS_SCRIPT_PATH}/job.bash

export MCMC_PRERUN_SAMPLES=40000
export MCMC_PRERUN_UPDATE_SIZE=500
export MCMC_PRERUN_CHAINS=1
export MCMC_PRERUN_PARALLEL=0

export PMC_CONVERGENCE="$PMC_CONVERGENCE --pmc-crop-highest-weights 200"
export PMC_CHUNKSIZE=4000
export PMC_CLUSTERS=40
export PMC_DOF=4
#export PMC_FINAL_CHUNKSIZE=250000
export PMC_GROUP_BY_RVALUE=2
export PMC_PATCH_LENGTH=150
export PMC_SKIP_INITIAL=0.5

export PMC_NUMBER_OF_JOBS=200
export LL_QUEUE=test
export LL_FINAL_QUEUE=serial
export PMC_POLLING_INTERVAL=60
export PMC_CLIENT_ARGV=

main $@
